### ISSUE TITLE
Tariff Alignment with Octopus Integration

### ISSUE THREAD

**Issue by solarjones** [stevebuk1/pv_opt#124]
VERSION = "3.8.5"

This morning I checked up on the automation and found the charing plan appearing to be stuck in the past and wanting to change at a more expensive rate. Also noticed its start SOC wasn't correct (much lower than the actual battery SOC). This would explain why to wanted to charge when it wasn't necessary. (10:47 time stamp) I tried toggling to ReadOnly and live mode but it didn't seem to make any new calculations. Then tried switching from predicted load to the new profile load modes. No change. Then I restarted AppDaemon which seem to do the trick.

Not sure if these logs contain enough, I can always switch debug=true if needed.

[pv_opt.log](https://github.com/fboundy/pv_opt/files/14285614/pv_opt.log)
[main.log](https://github.com/fboundy/pv_opt/files/14285615/main.log)
[error.log](https://github.com/fboundy/pv_opt/files/14285616/error.log)

Thanks for all your work in the recent days. I could hardly keep up with the fixes and versions that came out, brilliant stuff.

Regards

**Comment by fboundy** [comment]
Think this was probably caused by two weird Octopus Savings Events that had zero value and only lasted 3 minutes each. Mys system did the same. 3.8.6 should fix this.

**Comment by fboundy** [comment]
I initially though this was something else but looking at your error log it was caused by an empty list. Should be fixed with 3.8.7

**Comment by solarjones** [comment]
Got some errors on startup now...

[pv_opt.log](https://github.com/fboundy/pv_opt/files/14289404/pv_opt.log)
[main.log](https://github.com/fboundy/pv_opt/files/14289405/main.log)
[error.log](https://github.com/fboundy/pv_opt/files/14289406/error.log)

**Comment by fboundy** [comment]
Did these persist? I think there may have been some issues with the Octopus API last night.

**Comment by solarjones** [comment]
Yes, still not working this morning.
[error.log](https://github.com/fboundy/pv_opt/files/14293668/error.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/14293665/pv_opt.log)
[main.log](https://github.com/fboundy/pv_opt/files/14293667/main.log)

Anything I can do?

Octopus integration looks ok to me.

<img width="351" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/17c83623-1923-430b-ae7e-dad6ce91b90e">

**Comment by fboundy** [comment]
Hmmm - it’s reporting an error 602 from the octopus API query. Unfortunately I’ve no idea what this means! I’ll add some additional logging and get something out later today.

**Comment by fboundy** [comment]
Definitely some weird stuff going on with the Octopus API this evening

**Comment by fboundy** [comment]
There are some issues around OE tariff changes. Try restarting HA and AppDaemon.

**Comment by solarjones** [comment]
> There are some issues around OE tariff changes. Try restarting HA and AppDaemon.
> […](#)

No change after several HA & AppDaemon restarts.

**Comment by SzosszeNET** [comment]
@solarjones as usual butting in. Can't see your tariff mentioned in your pv_opt log.
Assume you have the octopus energy integration, can you check if the integration mentions what's your tariff?
Can you check if the entities are written?
In your pv_opt config I assume you have your tariff baked in and not your octopus API deeds?

If the integration doesn't write the data (see attached image. Disable it. Wait a little. Re-enable. Check pv_opt and the sensors. Just discovered this, however my charge was working by the looks of it.


![Screenshot_20240215-202916](https://github.com/fboundy/pv_opt/assets/32844005/0761e3c8-e39c-47c2-b09b-145856de2225)
![Screenshot_20240215-214053](https://github.com/fboundy/pv_opt/assets/32844005/f9f5ea10-8235-4ad4-96e3-48a9c1069257)

**Comment by solarjones** [comment]
The PV_OPT config I've left as default so not changed it.

I am using Octopus integration in HA
<img width="381" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/8af0b6de-5fae-498f-b154-293c4a891f3f">

It doesn't mention my tariff from what I can see. Where would I find this in HA?

And this was from a previous PV_OPT log when things were working:

22:10:00     INFO: Checking tariffs:
22:10:00     INFO: -----------------
22:10:00     INFO:   Import: E-1R-AGILE-FLEX-22-11-25-A               Start: 2024-02-04 13:00:00+0000 End: 2024-02-14 23:00:00+0000 
22:10:00     INFO:   Export: E-1R-OUTGOING-FIX-12M-19-05-13-A         Start: 2019-05-15 23:00:00+0000 End: N/A 
22:10:00     INFO: 
22:10:00     INFO: AGILE tariff detected. Rates will update at 16:00 daily
22:10:00     INFO:   - Tariffs OK

Just noticed the Tariff end date above was yesterday?! Even though I'm still on Agile, its not ended as per my OE account:
<img width="261" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/6e653fe8-4c35-401f-81c7-382bd6c74080">

Thanks for any other suggestions.

**Comment by solarjones** [comment]
<img width="1515" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/960ecbb2-2de1-4740-b7a8-322a63c3f7ac">
<img width="1519" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/7a57f9be-3dcc-4ce2-b516-9826f3382a1a">

**Comment by SzosszeNET** [comment]
Ah, so assume you restarted HA at 8 in the morning and that kicked back your integration into life.

I have the octopus API in my PV_OPT config, not sure now I said it does anything as it also looks at and finds the OE integration sensors. Guess would not hurt trying to add it? And removing if doesn't do anything.

octopus_account: !secret octopus_account
octopus_api_key: !secret octopus_api_key

Yes agile "ended" yesterday inline with the email octopus sent out about a month ago.
![Screenshot_20240215-204437](https://github.com/fboundy/pv_opt/assets/32844005/f1a4f095-0f4a-4fd2-b47a-e5f63f8de23b)

**Comment by solarjones** [comment]
As suggested, I added in Octopus API & Account, restarted HA and AppDaemon.  

At first I got some errors, then it started working...

**Comment by solarjones** [comment]
[pv_opt.log](https://github.com/fboundy/pv_opt/files/14308979/pv_opt.log)
[main.log](https://github.com/fboundy/pv_opt/files/14308980/main.log)
[error.log](https://github.com/fboundy/pv_opt/files/14308981/error.log)

**Comment by SzosszeNET** [comment]
Magic 🤣

**Comment by SzosszeNET** [comment]
But looks like it struggled to load consumption data?

**Comment by fboundy** [comment]
OK - so it was  detecting two octopus import entities - probably because of the changes to the Agile tariff and defaulted to the 1st one which I suspect is empty. I've added some logging which should confirm this if you can send me the `pv_opt.log`.

The issue with consumption seems to have been just the once. I've added a check that the history. 

Hopefully 3.8.3 addresses both.

**Comment by solarjones** [comment]
v 3.8.8 installed.

[pv_opt.log](https://github.com/fboundy/pv_opt/files/14312157/pv_opt.log)

**Comment by solarjones** [comment]
v 3.8.8 installed.
[pv_opt.log](https://github.com/fboundy/pv_opt/files/14312220/pv_opt.log)
Note, the MPAN was in plain text and not obfuscated.

**Comment by solarjones** [comment]
Noticed this too:

<img width="501" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/ff1c2349-6f57-40e2-86dd-5f0c731ad32e">

**Comment by fboundy** [comment]
OK - think I understand now on the tariff_code. The attribute doesn't exist for the old entity. Hence the error.

Fixed in 3.8.9

MPAN redaction should also be fixed.

**Comment by solarjones** [comment]
Installed 3.8.9

MPAN redaction working thanks.
[pv_opt.log](https://github.com/fboundy/pv_opt/files/14314092/pv_opt.log)

<img width="511" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/07df2d59-d775-43b9-b94d-1d99cc8dca56">


Do I need this in the config still?
octopus_account: !secret octopus_account
octopus_api_key: !secret octopus_api_key

Thanks.

**Comment by SzosszeNET** [comment]
It was just a hunch from me, feel free to remove.

**Comment by fboundy** [comment]
Looks like you do for now. There’s another tweak I need to make.

**Comment by SzosszeNET** [comment]
Looks like they is an OA integration update out addressing this issue

**Comment by solarjones** [comment]
Is this expected behaviour?
My SOC will be depleted well before its next planned charge slot.
<img width="495" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/14e605f3-d5ca-49c4-8566-abb61eebe248">

<img width="507" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/4d1b0975-ba51-4025-ba70-92a4b6ab0e55">

And there are cheaper slots prior to 03:00.
<img width="508" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/84eaa260-da69-490b-89d7-371a74cc2a0e">

Thanks

**Comment by solarjones** [comment]
I restarted AppDaemon and it stuck on Loading Tariffs. I then disabled the OE integration and reenabled, restarted AppDaemon, and it fired up just fine with the new charging plan.

<img width="494" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/775a8af8-47be-4991-ac3d-6bb3a54c4cce">

Thanks.

**Comment by spetrie13** [comment]
My charge plan is also not updating. It would appear that this is due to the tariff prices not being pulled from the Octopus API. The future price seems to be updated around 10:30 GMT in API but pv_opt does not seem to load the information. If I restart the App Demon then charge plan updates again. 
V3.8.8
Pre AppDemon restart:
![image](https://github.com/fboundy/pv_opt/assets/102915703/231a9dc5-b140-480c-bd11-2732d3e34a96)
![image](https://github.com/fboundy/pv_opt/assets/102915703/358bc683-9a27-4613-afc3-809da70bffdc)
![image](https://github.com/fboundy/pv_opt/assets/102915703/cb35e01a-26d3-4220-a937-56df30bdc214)

[error.log](https://github.com/fboundy/pv_opt/files/14331214/error.log)
[main.log](https://github.com/fboundy/pv_opt/files/14331215/main.log)
[pv_opt.log](https://github.com/fboundy/pv_opt/files/14331216/pv_opt.log)

Post AppDemon restart
![image](https://github.com/fboundy/pv_opt/assets/102915703/9e994049-9455-4df3-93ed-b2680550598a)
![image](https://github.com/fboundy/pv_opt/assets/102915703/9f73f393-8e6c-42d1-aa16-7aea74d05c62)

[main (1).log](https://github.com/fboundy/pv_opt/files/14331264/main.1.log)
[pv_opt (1).log](https://github.com/fboundy/pv_opt/files/14331266/pv_opt.1.log)

**Comment by solarjones** [comment]
There was a new release of Octopus Energy integration this morning. I downloaded it, restarted HA + AppDaemon. It appears to be working for the time being. Will see if it auto updates at 16:00 this afternoon.

**Comment by fboundy** [comment]
Ok that’s interesting. I have been busy since Saturday morning so not had a chance to look at anything yet

**Comment by fboundy** [comment]
I think I have found the source of these bugs and fixed in 3.8.10.

**Comment by fboundy** [comment]
Closing this as #132 supersedes it

**Comment by spetrie13** [comment]
Still not working for me with latest revision 3.8.10. On OE Go tarrif.
Optimises if I restart AppDemon. Tried modification the load margin and
toggle read to see if it would update, but no joy.

**Comment by fboundy** [comment]
Can you please provide the logs and then I can try to work our what it's doing?

**Comment by spetrie13** [comment]
Will have to download logs when I get home tomorrow. Can’t remotely
download the logs.
Will apply the 3.9.0 update tonight.

**Comment by fboundy** [comment]
3.9.2 now which fixes a few more bugs - mainly if you don't have export

**Comment by spetrie13** [comment]
Seems to be loading the tariff info today with V3.9.0 and providing an
optimised charge schedule.

Do you still want the logs?
Back home now

**Comment by fboundy** [comment]
No need if it all seems ok
