### ISSUE TITLE
Solax Integration - Mode Changes

### ISSUE THREAD

**Issue by solarjones** [stevebuk1/pv_opt#152]
3.10.0

[pv_opt.log](https://github.com/fboundy/pv_opt/files/14628869/pv_opt.log)
[error.log](https://github.com/fboundy/pv_opt/files/14628867/error.log)
[main.log](https://github.com/fboundy/pv_opt/files/14628868/main.log)

21:16:18 WARNING pv_opt: ------------------------------------------------------------
21:16:18 WARNING pv_opt: Unexpected error running initialize() for pv_opt
21:16:18 WARNING pv_opt: ------------------------------------------------------------
21:16:18 WARNING pv_opt: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/appdaemon/app_management.py", line 162, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.11/site-packages/appdaemon/utils.py", line 304, in run_in_executor
    response = future.result()
               ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/pv_opt.py", line 367, in initialize
    self.inverter.enable_timed_mode()
  File "/homeassistant/appdaemon/apps/pv_opt/solis.py", line 219, in enable_timed_mode
    self._solis_set_mode_switch(
  File "/homeassistant/appdaemon/apps/pv_opt/solis.py", line 453, in _solis_set_mode_switch
    status = self._solis_solax_solarman_mode_switch()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homeassistant/appdaemon/apps/pv_opt/solis.py", line 493, in _solis_solax_solarman_mode_switch
    code = codes[inverter_mode]
           ~~~~~^^^^^^^^^^^^^^^
KeyError: 'Self-Use'

I got this after doing several updates this evening on HA, one of which was the Solax Modbus integration. Even thought I've reverted, still get the above. I'll see if I can down grade the elements.

**Comment by fboundy** [comment]
Ok - let me know the Solax version numbers if you get anywhere.

**Comment by fboundy** [comment]
Just had a look at the Solax integration and he has expanded and changed the select entity for the inverter modes. Should be easy enough to fix but I’ll need to try to handle both versions which is a pain.

**Comment by fboundy** [comment]
I’ve just bumped mine to 24.03.3 and it looks like the names have been reverted but more options have been added. I think this shouldn’t cause a problem

**Comment by solarjones** [comment]
I've found (for me anyway) PV_Opt works with Solax Modbus 2024.03.1, but not after upgrading to 2024.3.3.

https://github.com/wills106/homeassistant-solax-modbus/releases 
Release notes under 2024.3.2 
Solis:
Added "Sync RTC Offset"
Adjusted names for "Energy Storage Control Switch"
Corrected "Battery Charge Current", "Battery ChargeDischarge Current" and "Battery Discharge Current" rounding. 

I got errors trying to RTC sync on both PV_Opt and Solis Helper. So looks like something has changed with that integration.

**Comment by solarjones** [comment]
> I’ve just bumped mine to 24.03.3 and it looks like the names have been reverted but more options have been added. I think this shouldn’t cause a problem
> […](#)
> On 17 Mar 2024 at 21:02 +0000, solarjones ***@***.***>, wrote: 3.10.0 pv_opt.log error.log main.log File "/homeassistant/appdaemon/apps/pv_opt/solis.py", line 493, in _solis_solax_solarman_mode_switch code = codes[inverter_mode] ~~~~~^^^^^^^^^^^^^^^ KeyError: 'Self-Use' I got this after doing several updates this evening on HA, one of which was the Solax Modbus integration. Even thought I've reverted, still get the above. I'll see if I can down grade the elements. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Did you totally deinstall Solax Modbus as per the suggestion? I did from integration and HACs, reloaded, restarted and then hit problems.

**Comment by fboundy** [comment]
Yep - I thought 03.3 fixed it but it doesn’t. Will have to have a look tomorrow. Rolling back to pre 24.03 might fix it

**Comment by fboundy** [comment]
Quick fix is to edit solis.py and on lines 8 and 11 replace SelfUse with Self-Use. Restart AD and all should be well.

Will patch properly tomorrow.

**Comment by fboundy** [comment]
This should be fixed in 3.11.0

**Comment by solarjones** [comment]
Just updated to 3.11.0 and 24.03.06 and when I tried Solis Sync RTC I got this:

<img width="650" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/1782d231-f703-478b-902d-b24bae9b53b1">

**Comment by SzosszeNET** [comment]
That's a solax issue

**Comment by solarjones** [comment]
Ah ok, you have that too?

**Comment by fboundy** [comment]
Agreed.

**Comment by fboundy** [comment]
I do with 24.03.4

**Comment by SzosszeNET** [comment]
Actually I had it with 24.03.3

**Comment by SzosszeNET** [comment]
Opened a bug report for this against solax

**Comment by solarjones** [comment]
Perhaps it's me being paranoid but I don't recall what mode my inverter usually operate in. Is this correct? Does the PV_Opt control this?

<img width="486" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/aa73b728-45a4-4caf-b655-03a712fdb711">

On the SolaX integration, it seems to list a few more than I remember:
<img width="383" alt="image" src="https://github.com/fboundy/pv_opt/assets/100320468/e57fe987-ddf6-48f1-a148-72b5f4f1dfb7">

Thanks.

**Comment by SzosszeNET** [comment]
Check history.
Tap on the icon in front of it to see when was what.
But otherwise self-use is correct when pv_opt isn't charging/discharging.

**Comment by solarjones** [comment]
Thanks for the History tip and highlighted a terminology change.

The SolaX Modbus integration has renamed the Energy_storage_control_switch mode names. What used to be mode enumeration 35 'Timed Charge/Discharge', is now 'Self-Use'. 

This explains what I noticed after installing 24.03.6 yesterday.

**Comment by fboundy** [comment]
Not quite. SelfUse has been renamed Self-Use and three Feed In Priority modes have been added. The indexes remain the same because the modes are controlled but-wise

**Comment by fboundy** [comment]
*bit-wise

**Comment by fboundy** [comment]
Something has got broken in the Solax/PV_Opt interface. I will need to investigate

**Comment by fboundy** [comment]
OK so here's the issue. Pre-24.03 the modes were:

    1: "Self-Use - No Grid Charging",
    3: "Timed Charge/Discharge - No Grid Charging",
    17: "Backup/Reserve - No Grid Charging",
    33: "Self-Use",
    35: "Timed Charge/Discharge",
    37: "Off-Grid Mode",
    41: "Battery Awaken",
    43: "Battery Awaken + Timed Charge/Discharge",
    49: "Backup/Reserve - No Timed Charge/Discharge",
    51: "Backup/Reserve",

24.03 onwards they are:

    1: "Self-Use - No Grid Charging",
    3: "Timed Charge/Discharge - No Grid Charging",
    17: "Backup/Reserve - No Grid Charging",
    33: "Self-Use - No Timed Charge/Discharge",
    35: "Self-Use",
    37: "Off-Grid Mode",
    41: "Battery Awaken",
    43: "Battery Awaken + Timed Charge/Discharge",
    49: "Backup/Reserve - No Timed Charge/Discharge",
    51: "Backup/Reserve",
    64: "Feed-in priority - No Grid Charging",
    96: "Feed-in priority - No Timed Charge/Discharge",
    98: "Feed-in priority",

The issue is 33 and 35. Fortunately he's also changed SelfUse to Self-Use so I can incorporate both versions. I'm testing a patch to 3.11 now which should resolve things I hope.

**Comment by fboundy** [comment]
Should be fixed by #156 in 3.11.1

**Comment by lazy-pete** [comment]
Hi - just updated Solax and PV_opt after it failed overnight (the RTC sync times were hours out so it was forcing the charge scheduled for middle of the night late). Still have an errror on RTC sync and pv_opt doesn’t seem to find number.solis_battery_minimum_soc  although I’ve confirmed it is present and set at 15% 

![IMG_6018](https://github.com/fboundy/pv_opt/assets/30950467/dd49c9de-111a-45b9-b752-b7b6e5f08a48)
![IMG_6019](https://github.com/fboundy/pv_opt/assets/30950467/931f4df8-dade-42cc-8342-c2c89174cc10)
![IMG_6020](https://github.com/fboundy/pv_opt/assets/30950467/942f73db-cc1d-4f2a-94b6-4479187f386b)
![IMG_6021](https://github.com/fboundy/pv_opt/assets/30950467/ab416230-2566-4c5a-9d0e-5c3a50d46a97)

**Comment by lazy-pete** [comment]
Actually- different error for RTC after updates - 

![IMG_6022](https://github.com/fboundy/pv_opt/assets/30950467/ebd71a93-c665-47c7-bdd5-e3fee831f23c)

**Comment by lazy-pete** [comment]
Seems to have sorted itself out apart from the second RTC sync error. 

Only thing I did was check the config.yaml - I unconnected the default dod line, which caused a duplication error, recommended it and things seemed to work after that.

**Comment by lazy-pete** [comment]
PS - I owe you some beers !

**Comment by fboundy** [comment]
Latest release has a "Don't buy me a beer or a coffee" section...
